#!/usr/bin/env bash
# Configures Nginx to listen on port 80

# Install necessary packages
sudo apt-get update
sudo apt-get install -y nginx

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
