#!/usr/bin/env bash
# Configures Nginx to listen on port 80
sudo apt update
sudo apt install -y nginx
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo service nginx restart
